name: bdaybot
channels:
- defaults
dependencies:
- arrow=0.12.0
- flake8=3.5.0
- isort=4.2.15
- pylint=1.7.4
- pytest=3.3.0
- python=3.6.3
- python-dateutil=2.6.1
- sqlalchemy=1.1.13
- pip:
  - apscheduler==3.4.0
  - slackclient==1.1.0
  - tox==2.9.1
  - tox-travis==0.10
